---
database:
  user: ""
  password: ""
  host: ""
  name: ""
  port: 5432
admin:
  enabled: false
  allow_from: []
  auth_token: ''
app:
  webapp_base_url: "http://localhost:3006"
  pagination:
    cursor_key: ""
  rjob:
    url: ""
    max_threads: 1
    prefix: "uno:r"
